FROM node:20-alpine

RUN apk add --no-cache docker-cli docker-cli-compose bash jq openssl

WORKDIR /app
COPY package.json .
RUN npm install --production
COPY . .

EXPOSE 3001
CMD ["node", "server.js"]
